version: '3'

volumes:
  local_postgres_data: {}
  local_solr_data: {}

services:
  db:
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    image: dprr_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
    restart: unless-stopped


  # Core config at /opt/solr/server/solr/mycores/dprr/conf
  solr:
    image: library/solr:6.6.5
    ports:
      - "8983:8983"
    volumes:
      - local_solr_data:/var/solr
    command:
      - solr-precreate
      - dprr

  # Remember to copy the schema! (Not automatic at present)
  # To build:
  # docker-compose -f local.yml run --rm web python manage.py build_solr_schema --configure-directory=/app/solr_config/config
  # then docker cp results to solr folder above
  web:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - solr