# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:46
from __future__ import unicode_literals

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('promrep', '0063_repopulate_person_dprr_id'),
    ]

    operations = [
    migrations.CreateModel(
            name='RelationshipInverse',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('inverse_relationship', models.ForeignKey(related_name='inverse', to='promrep.RelationshipType')),
                ('relationship', models.ForeignKey(to='promrep.RelationshipType')),
                ('sex', models.ForeignKey(to='promrep.Sex')),
            ],
        ) 
    ]
