# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:47
from __future__ import unicode_literals

from django.db import migrations,apps

def add_inverse(apps, relationship, sex, inverse_name):
    RelationshipInverse = apps.get_model("promrep", "RelationshipInverse")
    RelationshipType = apps.get_model("promrep", "RelationshipType")
    inverse = RelationshipType.objects.get(name=inverse_name)
    try:
        RelationshipInverse.objects.get(relationship=relationship, sex=sex, inverse=inverse)
    except ObjectDoesNotExist:
        RelationshipInverse.objects.get(relationship=relationship, sex=sex, inverse=inverse).save()


def add_inverse_relationship_types(apps, schema_editor):
    Sex = apps.get_model("promrep", "Sex")
    RelationshipType = apps.get_model("promrep", "RelationshipType")
    male = Sex.objects.get(name="Male")
    female = Sex.objects.get(name="Female")
    type = RelationshipType.objects.get(name="father of")
    add_inverse(apps, type, male, "son of")
    add_inverse(apps, type, female, "daughter of")
    type = RelationshipType.objects.get(name="mother of")
    add_inverse(apps, type, male, "son of")
    add_inverse(apps, type, female, "daughter of")
    type = RelationshipType.objects.get(name="married to")
    add_inverse(apps, type, male, "married to")
    add_inverse(apps, type, female, "married to")
    type = RelationshipType.objects.get(name="son of")
    add_inverse(apps, type, male, "father of")
    add_inverse(apps, type, female, "mother of")
    type = RelationshipType.objects.get(name="daughter of")
    add_inverse(apps, type, male, "father of")
    add_inverse(apps, type, female, "mother of")
    type = RelationshipType.objects.get(name="brother of")
    add_inverse(apps, type, male, "brother of")
    add_inverse(apps, type, female, "sister of")
    type = RelationshipType.objects.get(name="sister of")
    add_inverse(apps, type, male, "brother of")
    add_inverse(apps, type, female, "sister of")
    type = RelationshipType.objects.get(name="adoptive son of")
    add_inverse(apps, type, male, "adopted father of")
    add_inverse(apps, type, female, "adopted mother of")
    type = RelationshipType.objects.get(name="adoptive daughter of")
    add_inverse(apps, type, male, "adopted father of")
    add_inverse(apps, type, female, "adopted mother of")
    type = RelationshipType.objects.get(name="betrothed to")
    add_inverse(apps, type, male, "betrothed to")
    add_inverse(apps, type, female, "betrothed to")
    type = RelationshipType.objects.get(name="divorced from")
    add_inverse(apps, type, male, "divorced from")
    add_inverse(apps, type, female, "divorced from")
    type = RelationshipType.objects.get(name="nephew of")
    add_inverse(apps, type, male, "uncle of")
    add_inverse(apps, type, female, "aunt of")
    type = RelationshipType.objects.get(name="niece of")
    add_inverse(apps, type, male, "uncle of")
    add_inverse(apps, type, female, "aunt of")
    type = RelationshipType.objects.get(name="adoptive brother of")
    add_inverse(apps, type, male, "adoptive brother of")
    add_inverse(apps, type, female, "adoptive sister of")
    type = RelationshipType.objects.get(name="uncle of")
    add_inverse(apps, type, male, "nephew of")
    add_inverse(apps, type, female, "niece of")
    type = RelationshipType.objects.get(name="aunt of")
    add_inverse(apps, type, male, "nephew of")
    add_inverse(apps, type, female, "niece of")
    type = RelationshipType.objects.get(name="related to")
    add_inverse(apps, type, male, "related to")
    add_inverse(apps, type, female, "related to")
    type = RelationshipType.objects.get(name="halfsister of")
    add_inverse(apps, type, male, "halfbrother of")
    add_inverse(apps, type, female, "halfsister of")

    type = RelationshipType.objects.get(name="halfsister of")
    add_inverse(apps, type, male, "halfbrother of")
    add_inverse(apps, type, female, "halfsister of")

    type = RelationshipType.objects.get(name="great grandfather of")
    add_inverse(apps, type, male, "great grandson of")
    add_inverse(apps, type, female, "great grandson of")
    type = RelationshipType.objects.get(name="great grandmother of")
    add_inverse(apps, type, male, "great grandson of")
    add_inverse(apps, type, female, "great grandson of")
    type = RelationshipType.objects.get(name="grandfather of")
    add_inverse(apps, type, male, "grandson of")
    add_inverse(apps, type, female, "grandson of")
    type = RelationshipType.objects.get(name="grandmother of")
    add_inverse(apps, type, male, "grandson of")
    add_inverse(apps, type, female, "grandson of")

    type = RelationshipType.objects.get(name="grandson of")
    add_inverse(apps, type, male, "grandfather of")
    add_inverse(apps, type, female, "grandmother of")
    type = RelationshipType.objects.get(name="granddaughter of")
    add_inverse(apps, type, male, "grandfather of")
    add_inverse(apps, type, female, "grandmother of")

    type = RelationshipType.objects.get(name="stepfather of")
    add_inverse(apps, type, male, "stepson of")
    add_inverse(apps, type, female, "stepdaughter of")
    type = RelationshipType.objects.get(name="stepmother of")
    add_inverse(apps, type, male, "stepson of")
    add_inverse(apps, type, female, "stepdaughter of")
    type = RelationshipType.objects.get(name="cousin of")
    add_inverse(apps, type, male, "cousin of")
    add_inverse(apps, type, female, "cousin of")

    type = RelationshipType.objects.get(name="adoptive father of")
    add_inverse(apps, type, male, "adopted son of")
    add_inverse(apps, type, female, "adopted daughter of")

    type = RelationshipType.objects.get(name="adoptive mother of")
    add_inverse(apps, type, male, "adopted son of")
    add_inverse(apps, type, female, "adopted daughter of")

    type = RelationshipType.objects.get(name="stepson of")
    add_inverse(apps, type, male, "stepfather of")
    add_inverse(apps, type, female, "stepmother of")

    type = RelationshipType.objects.get(name="stepdaughter of")
    add_inverse(apps, type, male, "stepfather of")
    add_inverse(apps, type, female, "stepmother of")

    type = RelationshipType.objects.get(name="great grandson of")
    add_inverse(apps, type, male, "great grandfather of")
    add_inverse(apps, type, female, "great grandmother of")

    type = RelationshipType.objects.get(name="great granddaughter of")
    add_inverse(apps, type, male, "great grandfather of")
    add_inverse(apps, type, female, "great grandmother of")

    type = RelationshipType.objects.get(name="great uncle of")
    add_inverse(apps, type, male, "great nephew of")
    add_inverse(apps, type, female, "great niece of")

    type = RelationshipType.objects.get(name="adopted grandson of")
    add_inverse(apps, type, male, "adopted grandfather of")
    add_inverse(apps, type, female, "adopted grandmother of")
class Migration(migrations.Migration):

    dependencies = [
        ('promrep', '0064_create_inverse_20170227_1746'),
    ]

    operations = [
    	migrations.RunPython(add_inverse_relationship_types)
    ] 
