# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promrep", "0065_populate_inverse"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationshipassertion",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Editor Verified"),
        ),
    ]
