# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promrep', '0066_relationshipassertion_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationshipassertion',
            options={'ordering': ['relationship__order', 'relationship_number', 'id']},
        ),
    ]
