# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 10:15
from __future__ import unicode_literals

from django.db import migrations


def add_primarysource_defaults(apps, schema_editor):
    PrimarySource = apps.get_model("promrep", "PrimarySource")
    PrimarySource.objects.get_or_create(id=1,
                                        name='Not specified',
                                        abbrev_name='',
                                        biblio='')


class Migration(migrations.Migration):

    dependencies = [
        ('promrep', '0067_auto_20170301_1637'),
    ]

    operations = [
        migrations.RunPython(add_primarysource_defaults)
    ]
