# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 10:51


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promrep", "0068_add_primarysource_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarysourcereference",
            name="primary_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="promrep.PrimarySource",

            ),
        ),
    ]
