# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promrep', '0069_change_primarysourcereference_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustype',
            name='abbrev_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
