# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 10:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promrep", "0071_populate_statustype_abbrev_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="group",
            name="persons",
        ),
        migrations.RemoveField(
            model_name="group",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="postassertion",
            name="group",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
