# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promrep', '0072_remove_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postassertion',
            name='role',
        ),
        migrations.DeleteModel(
            name='RoleType',
        ),
    ]
