# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promrep', '0075_fix_grandfather'),
    ]

    operations = [
        migrations.AddField(
            model_name='postassertion',
            name='unknown',
            field=models.BooleanField(default=False),
        ),
    ]
