# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promrep', '0075_fix_grandfather'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uncertain',
            field=models.BooleanField(default=False),
        ),
    ]
