# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promrep', '0076_person_uncertain'),
        ('promrep', '0076_postassertion_unknown'),
    ]

    operations = [
    ]
