# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promrep', '0077_merge_20170801_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='era_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='era_to',
            field=models.IntegerField(default=0),
        ),
    ]
