# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 13:04


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailbase", "0002_blogpost_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "baseindexpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailbase.BaseIndexPage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailbase.baseindexpage",),
        ),
    ]
