# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailbase', '0002_blogpost_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('baseindexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailbase.BaseIndexPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailbase.baseindexpage',),
        ),
    ]
