name: 'dprr_openstack'

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro


  nginx:
    build:
      context: ..
      dockerfile: ./compose/nginx/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8001"
    volumes:
      - ../volumes/django/static:/usr/share/nginx/static:ro
    environment:
      VIRTUAL_HOST: ${DJANGO_ALLOWED_HOSTS}
      VIRTUAL_PATH: "~^/(static/|redist/|robots.txt)"
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: 8001

  django:
    build:
      context: ../
      dockerfile: ./compose/django/Dockerfile
    command: /start
    volumes:
      - ../volumes/django/static:/app/static
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      VIRTUAL_HOST: ${DJANGO_ALLOWED_HOSTS}
      VIRTUAL_PATH: "/"
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: 8000

  db:
    image: postgres:12.3
    volumes:
      - ../volumes/local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      timeout: 10s
      interval: 5s
      retries: 10

  elasticsearch:
    image: elasticsearch:7.10.1
    env_file:
      - .env
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped

  # Original repositories located at: /vol/poms3/webroot/rdf/repositories
  # files will be added manually to volumes on server
  rdf:
    image: tomcat:9
    restart: unless-stopped
    ports:
      - "8180:8080"
    volumes:
      - ../volumes/tomcat/logs:/usr/local/tomcat/logs/
      - ../volumes/tomcat/webapps:/usr/local/tomcat/webapps
      - ../volumes/tomcat/rdf4j:/usr/local/etc/rdf4j
    environment:
      VIRTUAL_HOST: ${DJANGO_ALLOWED_HOSTS}
      VIRTUAL_PATH: "/rdf"
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: 8080